### ISSUE TITLE
the colin27_zlib.bnii sample file has an incorrect Affine matrix

### ISSUE THREAD

**Issue by robertoostenveld** [fangq/jnifti#2]
```
>> jnii = loadjnifti('colin27_zlib.bnii')
jnii = 
  struct with fields:

    NIFTIHeader: [1×1 struct]
      NIFTIData: [181×217×181 uint8]

>> jnii.NIFTIHeader.Affine
ans =
  3×4 uint8 matrix
   1   0   0   0
   1   0   0   0
   1   0   0   0
```

I had expected it to be `eye(3,4)`, consistent with the `colin27_zlib.jnii` sample.

**Comment by fangq** [comment]
thanks @robertoostenveld, this should be fixed now. The issue is caused by a bug in the older version of jsonlab (which was used to generate the sample data), it is now fixed in the github version of jsonlab

https://github.com/fangq/jsonlab/commit/2e3344c93b6a3165049cead95e710bb7aabfafdd#diff-902f0766aa5af628d073e8c2309fc0744a1f8d0f4c882c977951c35b8f0d2e23R193

please pull the updated data samples again and test it again. It works for me with the github version of jsonlab.
